# This workflow was stared from the default GitHub workflow for .NET Core WP
# desktop apps. See more details here https://github.com/microsoft/github-actions-for-desktop-apps

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-test:
    runs-on: windows-2022    # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild. We need to use
    # msbuild instead of "dotnet build" due to this issue https://github.com/microsoft/WindowsAppSDK/issues/1652
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build
      run: msbuild StandardUI-Windows.sln /restore /p:Configuration=Release
