# This workflow was stared from the default GitHub workflow for .NET Core WP
# desktop apps. See more details here https://github.com/microsoft/github-actions-for-desktop-apps

name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]    # Later add Release when needed

    runs-on: windows-2019    # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: StandardUI.sln
      Test_Project_Path: tests/StandardUI.Base.Tests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test
